CREATE TABLE IF NOT EXISTS missao (
    codigo VARCHAR(50) PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    local VARCHAR(150) NOT NULL,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS admins (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(150),
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE admins
    ALTER COLUMN nome DROP NOT NULL,
    ALTER COLUMN ativo SET DEFAULT TRUE,
    ALTER COLUMN ativo SET NOT NULL;
