CREATE TABLE IF NOT EXISTS missao (
    codigo VARCHAR(50) PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    local VARCHAR(150) NOT NULL,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS admins (
    id VARCHAR(50) PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL
);
